name: Build Docker Image and Push to DockerHub

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    env: 
      DOCKER_REPOSITORY: gunwant11
      DOCKER_IMAGE_NAME: rf-uploader
      DOCKER_IMAGE_TAG: ${{ github.run_number }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadate (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: "latest"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
