name: Deploy to AKS

on:
  # push:
  #   branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "staging"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: gunwant11
      DOCKER_IMAGE_NAME: rf-uploader
      DOCKER_IMAGE_TAG: ${{ github.run_number }}
      DOCKER_REPOSITORY_URL: https://index.docker.io/v1/
      AKS_CLUSTER_NAME: aks-cluster
      AKS_RESOURCE_GROUP: rg-aks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}
      
      - name:  Create secret for AKS
        uses: Azure/k8s-create-secret@v1
        with:
          secret-name: project-secret
          container-registry-url: ${{ env.DOCKER_REPOSITORY_URL }}
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          secret-type: docker-registry

      
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
            kubernetes/ingress.yaml
          images: |
            gunwant11/rf-uploader:latest
          imagepullsecrets: |
            project-secret