name:  Deployment on AKS

# input staging or production as environment and deploy to the respective cluster my docker image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        type: choice
        default: "staging"
        options:
          - "production"
          - "staging"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: gunwant11
      DOCKER_IMAGE_NAME: rf-uploader
      DOCKER_IMAGE_TAG: ${{ github.run_number }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadate (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKER_REPOSITORY }}/${{ env.DOCKER_IMAGE_NAME }}
          tags: "latest"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: 'rg-aks'
          cluster-name: 'aks-cluster'
      
      - name:  Deploy on AKS
        uses: Azure/k8s-create-secret@v1
        with:
          secret-name: project-secret
          namespace: default
          container-registry-url: https://index.docker.io/v1/
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_PASSWORD }}
          secret-type: docker-registry

      
      - name:  Deploy on AKS
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/deployment.yaml
            kubernetes/service.yaml
            kubernetes/ingress.yaml
          images: |
            gunwant11/rf-uploader:lastest
          imagepullsecrets: |
            project-secret

