name: Create Deployment on AKS 

# input staging or production as environment and deploy to the respective cluster my docker image
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        default: 'staging'
        options:
          - 'production'
          - 'staging'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aksdemokasun
        resource-group: AKS-Demo-Cluster-RG

    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yml
          k8s/service.yml
        images: |
          kasunmadura/aks-demo:${{ github.sha }}
        
    
